### ISSUE TITLE
Time line for pitch shifting?

### ISSUE THREAD

**Issue by AmyXS** [echo66/PhaseVocoderJS#16]
Hi There, I found  this implementation of time stretching sound very good comparing to others, any plans for implementing the pitch shifting part soon?

**Comment by vikas-patel** [comment]
Hi @echo66 , I too found the time stretching output more cleaner compare to other libraries. Any plans or time estimates for the pitch shifting part?

**Comment by echo66** [comment]
@swan488 @vikas-patel sorry for such a late response. I have to reconfigure my github notifications in order to decrease the amount of stuff I'm notified about...back to the subject: well, I ceased to work on this project since I moved on to data science R&D. But I can give you advice on how to implement that.

**Comment by vikas-patel** [comment]
Hey, thanks for your reply. I am also moved to another project, so don't
need it now. btw, I was very impressed with quality audio output.

Thanks,

**Comment by AmyXS** [comment]
Thanks for the reply too echo66! I have then switched to use a C++ library instead. Thanks anyway! All the best with data science :)
